jwtSecret: "Test Secret"

spring:
  datasource:
    #spring.datasource.url=jdbc:mysql://localhost:3306/springsecuritydb?useSSL=false
    url: jdbc:h2:mem:testdb2
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop
    generate-ddl: true
  h2:
    console:
      enabled: true
