server:
  port: 8081

spring:
  application:
    name: jwt-spring-security-demo

  datasource:
    url: jdbc:mysql://localhost:3306/jwt_spring_security_demo?useSSL=false
    #url: jdbc:h2:mem:testdb
    username: root
    password: Test#12345
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
  h2:
    console:
      enabled: true

core:
  ### Replace this key with custom key
  jwt-secret: "SecretKeyToGenJWTsSecretKeyToGenJWTsSecretKeyToGenJWTsSecretKeyToGenJWTs"